spring:
  datasource:
    url: jdbc:mysql://192.168.31.31:4000/gharchive_dev
    username: root
    #    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.TiDBDialect
logging:
  file:
    path: .
    name: ossinsight-coss.log
coss:
  table-path: data/coss_invest.csv
  github-token: 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

